cart/urls.py
from django.urls import path 
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path 
from . import views 

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path 
from . import views 


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
]

shop/urls.py
from django.urls import path 
from . import views 

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    #path('index/', views.index, name='index'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms 
from django.utils.translation import gettext_lazy as _ 

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)] 

class CartAddproductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')#units of product количесвто единиц товара
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)#add in cart product 

cart/views.py
#from shop.recommender import Recommender
from coupons.forms import CouponApplyForm 
from django.shortcuts import render
from django.shortcuts import redirect 
from django.shortcuts import get_object_or_404 
from django.views.decorators.http import require_POST 
from shop.models import Product 
from .cart import Cart 
from .forms import CartAddproductForm 





#добавление add 
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddproductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail') 

#удаление remove
def cart_remove(request, product_id):
    cart = cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    if cart:
        return redirect('cart:cart_detail')
    return redirect('/')

#подробности details 
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddproductForm(initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm
    #r = Recommender()
    cart_products = [item['product'] for item in cart]
    #recommended_products = r.suggest_products_for(cart_products,max_results=4)
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})#'recommended_products': recommended_products})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    Ваша корзина
{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="container">
        <div class="row">
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Изображение</th>
                <th>Букет</th>
                <th>Количество</th>
                <th>Удалить из корзины</th>
                <th>Цена</th>
                <th>Общая сумма</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %} 
                {% with product=item.product %} 
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                                {{ item.update_quantity_form.quantity }} 
                                {{ item.update_quantity_form.update }} 
                                <input type="submit" value="Обновить">
                                {% csrf_token %} 
                            </form>
                        </td>
                        <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
                        <td class="num">{{ item.price }} руб.</td>
                        <td class="num">{{ item.total_price }} руб.</td>
                    </tr>
                {% endwith %} 
            {% endfor %} 
            </tbody>
            </table>
            </div>
            <div class="row">
                <div class="">
                <table>
                    <tbody>
            {% if cart.coupon %} 
                <tr class="subtotal">
                    <td>Стоимость без скидки</td>
                    <td colspan="4">{{ cart.get_total_price|floatformat:"2" }}</td>
                </tr>
            </div>
                <div class="col">
                <tr>
                    <td>Купон "{{ cart.coupon.code }}" со скидкой
                        {{ cart.coupon.discount }}% 
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        -{{ cart.get_discount|floatformat:"2" }} руб.
                    </td>
                </tr>
            {% endif %} 
            </div>
            <div class="col">
            <tr class="total">
                <td>Общая сумма</td>
                <td colspan="4"></td>
                <td class="num">
                {{ cart.get_total_price_after_discount|floatformat:"2" }} руб.
                </td>
                </tr>
        </tbody>
    </table>
    </div>
    {% if recommended_products %}
        <div class="col">
            <h3>С этим товаром покупают:</h3>
                {% for p in recommended_products %}
                    <div class="col">
                        <a href="{{ p.get_absolute_url }}">
                            <img src="{% if p.image %}{{ p.image.url }}{% else %}
                                {% static 'img/no_image.png' %}{% endif %}">
                        </a>
                        <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
                    </div>
                {% endfor %}
                </div>
                </div>
    {% endif %}
</div>
    <div class="col">
    <p>Форма для купона:</p>
        <form action="{% url 'coupons:apply' %}" method="POST">
                {{ coupon_apply_form }}
                <input type="submit" value="Купон готов">
                    {% csrf_token %}
        </form>
</div>
        <div class="col">
    <p class="text-right">
        {% csrf_token %}
        <a href="{% url 'shop:product_list' %}" class="button light">Продолжить покупки</a>
        <a href="{% url 'orders:order_create' %}" class="button">Подготовить заказ</a>
    </p>
    </div>
    </div>
    </div>
    </div>
{% endblock content %}
    
    